name: Builderman

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        lfs: true

    - name: Run script
      run: |
        sudo chmod +x buildscript.sh
        ./buildscript.sh
    - name: Push the changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
#    - name: Upload artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: Compiled images
#        path: |
#          ./kernel/root.zip
#          ./kernel/out.zip
