name: Build standalone kernel

on:
  push:
    branches:
      [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build setup
      run: |
        ./build.sh envcheck
        echo "date=$(date +'%Y%m%d-%H%M')" >> "$GITHUB_ENV"

    - name: Download source
      run: ./build.sh getsource
    
    - name: Download prebuilts & scripts
      run: ./build.sh gettools

    - name: Build kernel
      run: ./build.sh startbuild

    - name: Post-build
      run: |
        ./build.sh finalize
        echo "${VSUFFIX}" >> "$GITHUB_ENV"

    - name: Upload updater zip
      uses: actions/upload-artifact@v3
      with:
        name: AnyKernel3_veux-${{ env.sfx }}_${{ env.date }}
        path: ./AnyKernel3
    
    - name: Upload kernel modules
      uses: actions/upload-artifact@v3
      with: 
        name: Modules_veux-${{ env.sfx }}_${{ env.date }}
        path: ./out/android11-5.4/dist
